build with 9.6.1 as well

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -8,9 +8,9 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.15.20230211
+# version: 0.16
 #
-# REGENDATA ("0.15.20230211",["github","cabal.project"])
+# REGENDATA ("0.16",["github","cabal.project"])
 #
 name: Haskell-CI
 on:
@@ -28,6 +28,11 @@ jobs:
     strategy:
       matrix:
         include:
+          - compiler: ghc-9.6.1
+            compilerKind: ghc
+            compilerVersion: 9.6.1
+            setup-method: ghcup
+            allow-failure: false
           - compiler: ghc-9.4.4
             compilerKind: ghc
             compilerVersion: 9.4.4
@@ -45,11 +50,10 @@ jobs:
           apt-get update
           apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common libtinfo5
           mkdir -p "$HOME/.ghcup/bin"
-          curl -sL https://downloads.haskell.org/ghcup/0.1.18.0/x86_64-linux-ghcup-0.1.18.0 > "$HOME/.ghcup/bin/ghcup"
+          curl -sL https://downloads.haskell.org/ghcup/0.1.19.2/x86_64-linux-ghcup-0.1.19.2 > "$HOME/.ghcup/bin/ghcup"
           chmod a+x "$HOME/.ghcup/bin/ghcup"
-          "$HOME/.ghcup/bin/ghcup" config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml;
           "$HOME/.ghcup/bin/ghcup" install ghc "$HCVER" || (cat "$HOME"/.ghcup/logs/*.* && false)
-          "$HOME/.ghcup/bin/ghcup" install cabal 3.9.0.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
+          "$HOME/.ghcup/bin/ghcup" install cabal 3.10.1.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
         env:
           HCKIND: ${{ matrix.compilerKind }}
           HCNAME: ${{ matrix.compiler }}
@@ -65,7 +69,7 @@ jobs:
           echo "HC=$HC" >> "$GITHUB_ENV"
           echo "HCPKG=$HOME/.ghcup/bin/$HCKIND-pkg-$HCVER" >> "$GITHUB_ENV"
           echo "HADDOCK=$HOME/.ghcup/bin/haddock-$HCVER" >> "$GITHUB_ENV"
-          echo "CABAL=$HOME/.ghcup/bin/cabal-3.9.0.0 -vnormal+nowrap" >> "$GITHUB_ENV"
+          echo "CABAL=$HOME/.ghcup/bin/cabal-3.10.1.0 -vnormal+nowrap" >> "$GITHUB_ENV"
           HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')
           echo "HCNUMVER=$HCNUMVER" >> "$GITHUB_ENV"
           echo "ARG_TESTS=--enable-tests" >> "$GITHUB_ENV"
@@ -115,8 +119,8 @@ jobs:
       - name: install cabal-plan
         run: |
           mkdir -p $HOME/.cabal/bin
-          curl -sL https://github.com/haskell-hvr/cabal-plan/releases/download/v0.6.2.0/cabal-plan-0.6.2.0-x86_64-linux.xz > cabal-plan.xz
-          echo 'de73600b1836d3f55e32d80385acc055fd97f60eaa0ab68a755302685f5d81bc  cabal-plan.xz' | sha256sum -c -
+          curl -sL https://github.com/haskell-hvr/cabal-plan/releases/download/v0.7.3.0/cabal-plan-0.7.3.0-x86_64-linux.xz > cabal-plan.xz
+          echo 'f62ccb2971567a5f638f2005ad3173dba14693a45154c1508645c52289714cb2  cabal-plan.xz' | sha256sum -c -
           xz -d < cabal-plan.xz > $HOME/.cabal/bin/cabal-plan
           rm -f cabal-plan.xz
           chmod a+x $HOME/.cabal/bin/cabal-plan
@@ -133,6 +137,7 @@ jobs:
           echo "packages: $GITHUB_WORKSPACE/source/hgeometry-point" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/hgeometry-kernel" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/hgeometry" >> cabal.project
+          echo "packages: $GITHUB_WORKSPACE/source/hgeometry-ipe" >> cabal.project
           cat cabal.project
       - name: sdist
         run: |
@@ -154,6 +159,8 @@ jobs:
           echo "PKGDIR_hgeometry_kernel=${PKGDIR_hgeometry_kernel}" >> "$GITHUB_ENV"
           PKGDIR_hgeometry="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/hgeometry-[0-9.]*')"
           echo "PKGDIR_hgeometry=${PKGDIR_hgeometry}" >> "$GITHUB_ENV"
+          PKGDIR_hgeometry_ipe="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/hgeometry-ipe-[0-9.]*')"
+          echo "PKGDIR_hgeometry_ipe=${PKGDIR_hgeometry_ipe}" >> "$GITHUB_ENV"
           rm -f cabal.project cabal.project.local
           touch cabal.project
           touch cabal.project.local
@@ -162,6 +169,7 @@ jobs:
           echo "packages: ${PKGDIR_hgeometry_point}" >> cabal.project
           echo "packages: ${PKGDIR_hgeometry_kernel}" >> cabal.project
           echo "packages: ${PKGDIR_hgeometry}" >> cabal.project
+          echo "packages: ${PKGDIR_hgeometry_ipe}" >> cabal.project
           echo "package hgeometry-combinatorial" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package hgeometry-vector" >> cabal.project
@@ -172,16 +180,21 @@ jobs:
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package hgeometry" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
+          echo "package hgeometry-ipe" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           cat >> cabal.project <<EOF
           allow-newer: vector-circular:vector
           allow-newer: base
           allow-newer: template-haskell
+          allow-newer: hexpat:text
+          allow-newer: deepseq-generics:base
+          allow-newer: ghc-prim
 
           source-repository-package
             type:     git
             location: https://github.com/noinia/hiraffe
           EOF
-          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: $_ installed\n" unless /^(hgeometry|hgeometry-combinatorial|hgeometry-kernel|hgeometry-point|hgeometry-vector)$/; }' >> cabal.project.local
+          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: $_ installed\n" unless /^(hgeometry|hgeometry-combinatorial|hgeometry-ipe|hgeometry-kernel|hgeometry-point|hgeometry-vector)$/; }' >> cabal.project.local
           cat cabal.project
           cat cabal.project.local
       - name: dump install plan
@@ -218,6 +231,8 @@ jobs:
           cd ${PKGDIR_hgeometry_kernel} || false
           ${CABAL} -vnormal check
           cd ${PKGDIR_hgeometry} || false
+          ${CABAL} -vnormal check
+          cd ${PKGDIR_hgeometry_ipe} || false
           ${CABAL} -vnormal check
       - name: haddock
         run: |
